[package]
name = "cli-notes"
version = "0.2.0"
edition = "2024"
authors = ["Iskander Vane <iskander@ivane.dev>"]
license = "MIT"
description = "A simple CLI tool for managing notes"
homepage = "https://github.com/ivane/cli-notes"

[[bin]]
name = "cn"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"] }
rusqlite = { version = "0.40.1", features = ["bundled"] }
